before_install:
    - sudo apt-get update
    - sudo apt-get install r-base
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"limma\")" | sudo R --no-save
language: java
jdk:
    - oraclejdk7
    - openjdk7
